name: Health Check

on:
  push:
    branches: [ main ]

jobs:
  helth_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          # Check the following URLs one by one sequentially
          url: https://full-stack-open-pokedex-csux.onrender.com
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
      - name: Success Discord Notify
        uses: EDUJOS/ds-webhook@v1.0.0
        if: success()
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Health Check Passed!
          description: 'URL: https://full-stack-open-pokedex-csux.onrender.com'
      - name: Failure Discord Notify
        uses: EDUJOS/ds-webhook@v1.0.0
        if: failure()
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Health Check Failed!
          description: 'URL: https://full-stack-open-pokedex-csux.onrender.com'
      