name: Health Check

on:
  push:
    branches: [ main ]

jobs:
  helth_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Check the deployed service URL
        uses: Mustafakhn/health-check-action@v1
        with:
          # Check the following URLs one by one sequentially
          website_url: https://full-stack-open-pokedex-csux.onrender.com
      - name: Success Discord Notify
        uses: stegzilla/discord-notify@v2
        if: success()
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Health Check Passed!
          message: 'URL: https://full-stack-open-pokedex-csux.onrender.com'
      - name: Failure Discord Notify
        uses: stegzilla/discord-notify@v2
        if: failure()
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Health Check Failed!
          message: 'URL: https://full-stack-open-pokedex-csux.onrender.com'
      